[package]
name = "bevy_verlet"
version = "0.1.1"
edition = "2021"
authors = ["Felix de Maneville <felix.maneville@gmail.com>"]
repository = "https://github.com/ManevilleF/bevy_verlet"
license-file = "./LICENSE"
exclude = ["examples", "docs"]
description = "Verlet physics implementation in bevy"
keywords = ["verlet", "physics", "bevy", "cloth"]
categories = ["game-engines", "game-development"]
readme = "README.md"
documentation = "https://docs.rs/bevy_verlet"

[features]
default = []
debug = ["bevy_prototype_debug_lines"]

[dependencies]

[dependencies.bevy]
version = "0.5"
default-features = false

[dependencies.bevy_prototype_debug_lines]
version = "0.3"
optional = true

[dev-dependencies]

[dev-dependencies.bevy]
version = "0.5"
features = ["render", "bevy_winit", "png", "x11", "bevy_wgpu"]
default-features = false