[package]
name = "bevy_verlet"
version = "0.1.0"
edition = "2018"
authors = ["Felix de Maneville <felix.maneville@gmail.com>"]
repository = "https://github.com/ManevilleF/bevy_verlet"
license-file = "./LICENSE"

[features]
default = ["3d_collisions", "2d_collisions"]
debug = ["bevy_prototype_debug_lines"]
3d_collisions = []
2d_collisions = []

[dependencies]

[dependencies.bevy]
version = "0.5"
default-features = false

[dependencies.bevy_prototype_debug_lines]
version = "0.3"
optional = true

[dev-dependencies]
bevy_prototype_lyon = "0.3"

[dev-dependencies.bevy]
version = "0.5"
features = ["render", "bevy_winit", "png", "x11", "bevy_wgpu"]
default-features = false