[package]
name = "bevy_verlet"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["2D", "3D"]
2D = []
3D = []
debug = ["bevy_prototype_debug_lines"]

[dependencies]
bevy = "0.5"
bevy_prototype_debug_lines = { version = "0.3", optional = true }
rand = "0.8"
