name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: cargo build --verbose

  build_features:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 2D collisions
        run: cargo build --verbose --no-default-features --features 2d_collisions
      - name: 3D collisions
        run: cargo build --verbose --no-default-features --features 3d_collisions
      - name: debug
        run: cargo build --verbose --no-default-features --features debug
      - name: all features
        run: cargo build --verbose --all-features
      - name: no default features
        run: cargo build --verbose --no-default-features
        
  build_examples:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: cargo build --verbose --examples

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: test
        run: cargo test --tests --all-features

  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check Formatting
        run: cargo fmt --all -- --check

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cargo clippy installation
        run: rustup component add clippy
      - name: Cargo clippy check
        run: cargo clippy --all-features --all --tests -- -D warnings

  rustdoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: rustdoc
        run: cargo rustdoc --all-features